#!/usr/bin/env python3
"""
GuardAI ML — Download Pre-Trained Model

Downloads a real, open-source, pre-trained phishing URL classifier from
Hugging Face: pirocheto/phishing-url-detection

This is NOT the synthetic model in train_model.py / model.json. It's a
genuinely pre-trained model (Linear SVM) trained on a real public dataset
of 11,400+ labeled phishing/legitimate URLs (not generated by us), so it
requires no training data or training step on your end — you just
download the file and use it.

Published metrics from the model card (https://huggingface.co/pirocheto/phishing-url-detection):
  ROC-AUC:   0.987
  Accuracy:  0.949
  F1:        0.949
  Precision: 0.948
  Recall:    0.950

License: MIT. Distributed as ONNX (not pickle) — avoids the deserialization
security risk that comes with loading arbitrary .pkl files from the internet.

USAGE (run this on a machine with internet access — NOT inside a locked-down
sandbox/CI environment that blocks huggingface.co):

    cd backend
    pip install huggingface_hub --break-system-packages
    python3 -m ml.download_pretrained_model

This saves the model to ml/pretrained/model.onnx. The backend will
automatically detect and use it on next restart — see ml/predict.py.
If this file is absent, the system safely falls back to the synthetic
logistic regression model (ml/model.json) with no errors.
"""

import sys
from pathlib import Path

REPO_ID = "pirocheto/phishing-url-detection"
FILENAME = "model.onnx"

DEST_DIR = Path(__file__).resolve().parent / "pretrained"
DEST_PATH = DEST_DIR / "model.onnx"


def main():
    try:
        from huggingface_hub import hf_hub_download
    except ImportError:
        print("ERROR: huggingface_hub is not installed.")
        print("Run: pip install huggingface_hub --break-system-packages")
        sys.exit(1)

    DEST_DIR.mkdir(parents=True, exist_ok=True)

    print(f"Downloading {FILENAME} from {REPO_ID}...")
    print("(This contacts huggingface.co — make sure outbound HTTPS is allowed")
    print(" from this machine; it will NOT work inside a network-restricted sandbox.)")

    try:
        downloaded_path = hf_hub_download(repo_id=REPO_ID, filename=FILENAME)
    except Exception as exc:
        print(f"\nDownload failed: {exc}")
        print("\nIf you're behind a restrictive firewall/proxy, you can also download")
        print(f"the file manually from:")
        print(f"  https://huggingface.co/{REPO_ID}/resolve/main/{FILENAME}")
        print(f"and place it at: {DEST_PATH}")
        sys.exit(1)

    import shutil
    shutil.copy(downloaded_path, DEST_PATH)

    size_kb = DEST_PATH.stat().st_size / 1024
    print(f"\nModel downloaded successfully: {DEST_PATH} ({size_kb:.1f} KB)")
    print("\nRestart the backend (or the gunicorn container) for it to be picked up.")
    print("Verify with: curl http://localhost:8000/v1/health  (check ml_model.pretrained_loaded)")


if __name__ == "__main__":
    main()
